### ISSUE TITLE
Running with wordembed_type none doesn't work

### ISSUE THREAD

**Issue by EmilStenstrom** [kaniblu/pytorch-bilstmcrf#4]
I run train.py with these settings:

```
python train.py --feats_path ../suc_train_feats.txt --feats_vocab ../suc_vocab_feats.pkl --labels_path ../suc_train_labels.txt --labels_vocab ../suc_vocab_labels.pkl --save_dir models --hidden_dim 100 --wordembed_type none
```

And get this error: 

```
Loading vocabulary...
Initializing model...
Traceback (most recent call last):
  File "train.py", line 474, in <module>
    main()
  File "train.py", line 369, in main
    dropout_prob=args.dropout_prob)
  File "/Users/<user>/Projects/<proj>/pytorch-bilstmcrf/model.py", line 160, in __init__
    assert len(word_vocabs) == len(word_dims)
TypeError: object of type 'NoneType' has no len()
```

Are word embeddings required? Mind showing an example of how to use them?

**Comment by kaniblu** [comment]
The error is caused by not specifying word embedding dimensions (which is typically 300) and not because you did not provide pre-trained word embeddings. You could specify pre-trained word embeddings by choosing `glove` or `fasttext` (`--wordembed_type`). In the case of `glove`, you need to specify where the `glove` file is (e.g. `--wordembed_path glove.840B.300d.txt`) and whether you would like to freeze your word embeddings (`--wordembed_freeze`). Check out sample config files for examples.

**Comment by EmilStenstrom** [comment]
@kaniblu So are you saying that you HAVE TO specify embeddings, even though "--wordembed_type none" is a valid option?

**Comment by kaniblu** [comment]
No, you don't have use pre-trained embeddings, but you must specify word dimensions (e.g. `--word_dim 300`). The model would not know how to initialize all the hidden layer dimensions otherwise.

**Comment by EmilStenstrom** [comment]
So word_dim is required! Maybe that's a good change to train.py? 

Specifying word_dim seems to hint that **wordembed_freeze** and **wordebed_path** are required too:

```
$ python train.py --feats_path ../suc_train_feats.txt --feats_vocab ../suc_vocab_feats.pkl --labels_path ../suc_train_labels.txt --labels_vocab ../suc_vocab_labels.pkl --save_dir models --hidden_dim 100 --wordembed_type none --word_dim 300
Loading vocabulary...
Initializing model...
Loading word embeddings...
Traceback (most recent call last):
  File "train.py", line 474, in <module>
    main()
  File "train.py", line 378, in main
    args.wordembed_freeze)):
TypeError: zip argument #3 must support iteration
```

**Comment by EmilStenstrom** [comment]
Even setting them as dummy values seems to crash because save_dir isn't a PathLike object? 

```
python train.py --feats_path ../suc_train_feats.txt --feats_vocab ../suc_vocab_feats.pkl --labels_path ../suc_train_labels.txt --labels_vocab ../suc_vocab_labels.pkl --save_dir ../models --hidden_dim 100 --wordembed_type none --word_dim 300 --wordembed_path / --wordembed_freeze 1
Loading vocabulary...
Initializing model...
Loading word embeddings...
Traceback (most recent call last):
  File "train.py", line 474, in <module>
    main()
  File "train.py", line 415, in main
    config_path = os.path.join(save_dir, os.path.basename(args.config))
  File "/Users/EmilStenstrom/Envs/NER/bin/../lib/python3.6/posixpath.py", line 144, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by kaniblu** [comment]
@EmilStenstrom the error is likely due to not considering the possibility of running the script with command-line arguments (it was designed to work with configuration files at first). I will soon update with a working example (#5), but meanwhile you could try writing the same arguments in a yaml file then referencing the file with `--config` option.

Not exactly the same, but a comparable example configuration file is available [here](https://github.com/kaniblu/pytorch-skipthoughts/blob/master/examples/train.yml). Apologies for the frustrating situation. (This repo was just part of an in-house project, so we never expected this to gain any attention.)

**Comment by EmilStenstrom** [comment]
@kaniblu Thanks! 

I'm so happy that you decided to release this to the public at all (and you really have no obligation to provide support like this). I'm happy that you do! I'm not really frustrated, just confused :)
